### ISSUE TITLE
FR1. Splash Page Containing Logo and Name 

### ISSUE THREAD

**Issue by gwengueccia** [WSU-4110/QuickFitCuisine#1]
|FR1.  Splash Page Containing Logo and Name|
|---|
|**Goal**: A splash page with the app name and logo will appear when the user opens the app.
**Stakeholders:** Users|
| **Description:** When the user opens the app, the app logo will appear with the app name. This is needed so that the app can load in the background.  |
| **Origin:** During a meeting, team members brainstormed initial software requirements. This requirement was created in that meeting. |
| **Version:** 1.0  |
|**Date:** 09/18/2022
|  **Priority:** 3 |

**Comment by SyedNaumanTanveer** [comment]
Switched from developing android application to website. Did not need a splash page then.
