### ISSUE TITLE
FR14. Font Size

### ISSUE THREAD

**Issue by Migen123** [WSU-4110/QuickFitCuisine#11]
|FR14.  Font Size |
|---|
|**Goal**: Another option is to change the font size setting.
**Stakeholders:** Users|
| **Description:** This option would allow for the user to control the font size of the elements that they can search but also the text of the results and text spread throughout the user interface in order to provide the users with more accessibility options. |
| **Origin:** During a meeting, team members brainstormed initial software requirements. This requirement was created in that meeting.|
| **Version:** 1.0  |
|**Date:** 09/18/2022
|  **Priority:** 5 |

**Comment by SyedNaumanTanveer** [comment]
This function was low priority, hence not implemented in immediate release of website.
