### ISSUE TITLE
FR12. Settings Page

### ISSUE THREAD

**Issue by gb3896** [WSU-4110/QuickFitCuisine#13]
|FR12.  Settings Page|
|---|
|**Goal**: A settings page so users can choose their app preferences.
**Stakeholders:** Users|
| **Description:** Users should be able to open a settings page with multiple options. Options include, but are not limited to, a dark mode toggle and the ability to change the size of the font in the app. |
| **Origin:** During a meeting, team members brainstormed initial software requirements. This requirement was created in that meeting.|
| **Version:** 1.0  |  
|**Date:** 09/18/2022
|  **Priority:** 4 |

**Comment by SyedNaumanTanveer** [comment]
It was a low priority, hence not put in the initial release of website, will be brought in future versions.
