### ISSUE TITLE
FR15. Ingredients Not Present

### ISSUE THREAD

**Issue by Migen123** [WSU-4110/QuickFitCuisine#15]
|FR15.  Ingredients Not Present|
|---|
|**Goal**: If the database does not contain any recipes for the ingredients that the user selected, the app will suggest ingredients to buy that would result in a valid recipe.
**Stakeholders:** Customers|
| **Description:** This approach would ensure that even if no recipes are discovered with the selections that the user has made then it would provide the closest matching recipes that include those selection and at least one other ingredient that the user has not chosen. It will also be an option that the user can select alongside their food items meaning the results could contain a recipe with an ingredient that the user did not select and it would be clearly marked alongside the result what ingredient was missing.  |
| **Origin:** Based on initial project specification   document, team 
members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/18/2022
|  **Priority:** 5 |

**Comment by SyedNaumanTanveer** [comment]
Since it was priority 5, this feature will not be rolled out in the initial website. It will be added in future, if work continues on the website.
