### ISSUE TITLE
FR13.  Dark Mode  

### ISSUE THREAD

**Issue by Migen123** [WSU-4110/QuickFitCuisine#4]
|FR13.  Dark Mode|
|---|
|**Goal**: An option for the user to enable dark mode setting.  
**Stakeholders:** Users|
| **Description:** Allowing the user to have greater control of the settings of the interface and of the results so that if they wish for a dark mode with lower screen brightness than normal then they can quickly enable it with a button close on the main page.  |
| **Origin:** During a meeting, team members brainstormed initial software requirements. This requirement was created in that meeting.|
| **Version:** 1.0  |
|**Date:** 09/18/2022
|  **Priority:** 5 |

**Comment by SyedNaumanTanveer** [comment]
Low priority, hence not implemented in initial release of website.
