### ISSUE TITLE
FR10. Images

### ISSUE THREAD

**Issue by gb3896** [WSU-4110/QuickFitCuisine#6]
|FR10.  Images|
|---|
|**Goal**:  Ingredient buttons and recipe tile should also display an image of the finished dish when hovered over with the mouse.
**Stakeholders:** Users|
| **Description:** When viewing a recipe, an image will load when hovered over the recipe tile showing what the finished dish looks like. This should let the user see what the final product looks like and help them decide whether it’s worth creating. |
| **Origin:** During a meeting, team members brainstormed initial software requirements. This requirement was created in that meeting.|
| **Version:** 1.0  |  
|**Date:** 09/18/2022  
|  **Priority:** 5 |

**Comment by SyedNaumanTanveer** [comment]
Low priority, hence not added in initial release of website.
