### ISSUE TITLE
FR11. Sorting by Popularity

### ISSUE THREAD

**Issue by gb3896** [WSU-4110/QuickFitCuisine#9]
|FR11.  Sorting by Popularity|
|---|
|**Goal**: The user should have the option to view recipes sorted by the most popular.
**Stakeholders:** Users|
| **Description:** The user might be indecisive about which recipe to choose. The user should have the option to view the recipes in order of most popular or most viewed. This can help the user decide what to make based on other users’ choices. |
| **Origin:** During a meeting, team members brainstormed initial software requirements. This requirement was created in that meeting.|
| **Version:** 1.0  |  
|**Date:** 09/18/2022  
|  **Priority:** 5 |

**Comment by SyedNaumanTanveer** [comment]
Since this was low priority functional requirement. It was not implemented in initial website release. Will be added in the future, if work continues on website.
